[project]
name = "parsing-tests"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11,<3.12"
dependencies = [
    "requests>=2.32.0",
    "python-dotenv>=1.0.1",
    "pymupdf>=1.26.6",
]
